version: "3"
services:
  influxdb:
    image: influxdb:1.6.2
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:5.2.4
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb
  puppeteer:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    volumes:
      - ./output:/app
    depends_on:
      - grafana
